blackfire:
  image: blackfire/blackfire
  environment:
    - BLACKFIRE_SERVER_ID
    - BLACKFIRE_SERVER_TOKEN

flobmysql:
  build: ./mysql/
  volumes:
    - ./mysql/data/:/var/lib/mysql

flobphp:
  build: ./php/
  links:
    - blackfire
    - flobmysql
  volumes:
    - ../:/app
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  environment:
    - BLACKFIRE_CLIENT_ID
    - BLACKFIRE_CLIENT_TOKEN
  ports:
    - "8080:80"

flobtool:
  build: ./tool/
  links:
    - flobphp
    - flobmysql
  volumes:
    - ../:/app
    - ~/.composer:/var/www/.composer
    - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:ro
    - $SSH_AUTH_SOCK:/tmp/ssh_auth_sock:ro
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  environment:
    - SSH_AUTH_SOCK=/tmp/ssh_auth_sock
